import { writeFile } from "node:fs/promises";
import type { HttpExchange, Session } from "./session.js";
import { isSensitiveHeader, redactHeaders } from "./redact.js";

export function buildReport(session: Session): unknown {
  const passed = session.results.filter((r) => r.ok).length;
  return {
    spec: session.spec ? { title: session.spec.title, version: session.spec.version, baseUrl: session.spec.baseUrl } : null,
    summary: { assertions: session.results.length, passed, failed: session.results.length - passed, requests: session.history.length },
    results: session.results,
    requests: session.history.map((e) => ({
      method: e.request.method,
      url: e.request.url,
      status: e.response.status,
      durationMs: e.durationMs,
    })),
  };
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function toJUnit(session: Session): string {
  const failures = session.results.filter((r) => !r.ok).length;
  const cases = session.results
    .map((r) => {
      const body = r.ok ? "" : `<failure message="${xmlEscape(r.detail)}"/>`;
      return `    <testcase name="${xmlEscape(r.name)}" time="0">${body}</testcase>`;
    })
    .join("\n");
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<testsuites tests="${session.results.length}" failures="${failures}">`,
    `  <testsuite name="open-api-mcp" tests="${session.results.length}" failures="${failures}">`,
    cases,
    `  </testsuite>`,
    `</testsuites>`,
  ].join("\n");
}

function harHeaders(headers: Record<string, string>): { name: string; value: string }[] {
  return Object.entries(redactHeaders(headers)).map(([name, value]) => ({ name, value }));
}

function harEntry(e: HttpExchange): unknown {
  const u = new URL(e.request.url);
  return {
    startedDateTime: new Date(e.startedAt).toISOString(),
    time: e.durationMs,
    request: {
      method: e.request.method,
      url: e.request.url,
      httpVersion: "HTTP/1.1",
      headers: harHeaders(e.request.headers),
      queryString: [...u.searchParams.entries()].map(([name, value]) => ({ name, value })),
      postData: e.request.body ? { mimeType: "application/json", text: e.request.body } : undefined,
      headersSize: -1,
      bodySize: e.request.body ? e.request.body.length : 0,
    },
    response: {
      status: e.response.status,
      statusText: e.response.statusText,
      httpVersion: "HTTP/1.1",
      headers: harHeaders(e.response.headers),
      content: { size: e.response.bodyText.length, mimeType: e.response.mimeType, text: e.response.bodyText },
      headersSize: -1,
      bodySize: e.response.bodyText.length,
    },
    cache: {},
    timings: { send: 0, wait: e.durationMs, receive: 0 },
  };
}

export function toHAR(session: Session): unknown {
  return {
    log: {
      version: "1.2",
      creator: { name: "open-api-mcp", version: "0.1.0" },
      entries: session.history.map(harEntry),
    },
  };
}

function jStr(s: string): string {
  return JSON.stringify(s);
}

function safeOrigin(url: string): string | undefined {
  try {
    return new URL(url).origin;
  } catch {
    return undefined;
  }
}

function jestCase(e: HttpExchange): string {
  const u = new URL(e.request.url);
  const path = u.pathname + u.search;
  const method = e.request.method.toUpperCase();

  const headerLines: string[] = [];
  let hasAuth = false;
  for (const [k, v] of Object.entries(e.request.headers)) {
    const lower = k.toLowerCase();
    if (isSensitiveHeader(k)) {
      hasAuth = true;
      continue;
    }
    if (lower === "host" || lower === "content-length") continue;
    headerLines.push(`        ${jStr(k)}: ${jStr(v)},`);
  }

  const ct = e.response.headers["content-type"] ?? e.response.mimeType ?? "";
  const isJson = /json/i.test(ct);

  const init: string[] = [`      method: ${jStr(method)},`];
  if (headerLines.length || hasAuth) {
    init.push("      headers: {", ...headerLines, "        ...authHeaders(),", "      },");
  }
  if (e.request.body !== undefined && method !== "GET" && method !== "HEAD") {
    init.push(`      body: ${jStr(e.request.body)},`);
  }

  const lines = [
    `  it(${jStr(`${method} ${path} -> ${e.response.status}`)}, async () => {`,
    `    const res = await fetch(BASE + ${jStr(path)}, {`,
    ...init,
    "    });",
    `    expect(res.status).toBe(${e.response.status});`,
  ];
  if (isJson) {
    lines.push("    const body = await res.json();", "    expect(body).toBeDefined();");
  }
  lines.push("  });");
  return lines.join("\n");
}

export function toJest(session: Session): string {
  const origin =
    (session.history[0] && safeOrigin(session.history[0].request.url)) ||
    session.spec?.baseUrl ||
    session.baseUrl ||
    "http://localhost";
  const title = session.spec?.title ?? "API";

  const header = [
    "/**",
    " * Generated by open-api-mcp from a live test session.",
    " * Replays each executed request and asserts the observed status code.",
    " * Override the target with API_BASE_URL; provide auth via API_AUTH / API_KEY / API_COOKIE.",
    " * E2E flows are intentionally excluded — this is HTTP contract replay.",
    " */",
    "",
    `const BASE = process.env.API_BASE_URL || ${jStr(origin)};`,
    "",
    "function authHeaders() {",
    "  return {",
    "    ...(process.env.API_AUTH ? { authorization: process.env.API_AUTH } : {}),",
    '    ...(process.env.API_KEY ? { "x-api-key": process.env.API_KEY } : {}),',
    "    ...(process.env.API_COOKIE ? { cookie: process.env.API_COOKIE } : {}),",
    "  };",
    "}",
    "",
  ].join("\n");

  const cases =
    session.history.length === 0
      ? '  it.todo("no requests were recorded in this session");'
      : session.history.map(jestCase).join("\n\n");

  return [header, `describe(${jStr(`${title} — contract replay`)}, () => {`, cases, "});", ""].join("\n");
}

export async function exportReport(
  session: Session,
  args: { format: "junit" | "har" | "json" | "jest"; path?: string },
): Promise<unknown> {
  let content: string;
  if (args.format === "junit") content = toJUnit(session);
  else if (args.format === "har") content = JSON.stringify(toHAR(session), null, 2);
  else if (args.format === "jest") content = toJest(session);
  else content = JSON.stringify(buildReport(session), null, 2);

  if (args.path) {
    await writeFile(args.path, content, "utf8");
    return { written: args.path, format: args.format, bytes: content.length };
  }
  return { format: args.format, content };
}
