import { writeFile } from "node:fs/promises";
import type { HttpExchange, Session } from "./session.js";
import { isSensitiveHeader, redactHeaders } from "./redact.js";

export function buildReport(session: Session): unknown {
  const passed = session.results.filter((r) => r.ok).length;
  return {
    spec: session.spec ? { title: session.spec.title, version: session.spec.version, baseUrl: session.spec.baseUrl } : null,
    summary: { assertions: session.results.length, passed, failed: session.results.length - passed, requests: session.history.length },
    results: session.results,
    requests: session.history.map((e) => ({
      method: e.request.method,
      url: e.request.url,
      status: e.response.status,
      durationMs: e.durationMs,
    })),
  };
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function toJUnit(session: Session): string {
  const failures = session.results.filter((r) => !r.ok).length;
  const cases = session.results
    .map((r) => {
      const body = r.ok ? "" : `<failure message="${xmlEscape(r.detail)}"/>`;
      return `    <testcase name="${xmlEscape(r.name)}" time="0">${body}</testcase>`;
    })
    .join("\n");
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<testsuites tests="${session.results.length}" failures="${failures}">`,
    `  <testsuite name="open-api-mcp" tests="${session.results.length}" failures="${failures}">`,
    cases,
    `  </testsuite>`,
    `</testsuites>`,
  ].join("\n");
}

function harHeaders(headers: Record<string, string>): { name: string; value: string }[] {
  return Object.entries(redactHeaders(headers)).map(([name, value]) => ({ name, value }));
}

function harEntry(e: HttpExchange): unknown {
  const u = new URL(e.request.url);
  return {
    startedDateTime: new Date(e.startedAt).toISOString(),
    time: e.durationMs,
    request: {
      method: e.request.method,
      url: e.request.url,
      httpVersion: "HTTP/1.1",
      headers: harHeaders(e.request.headers),
      queryString: [...u.searchParams.entries()].map(([name, value]) => ({ name, value })),
      postData: e.request.body ? { mimeType: "application/json", text: e.request.body } : undefined,
      headersSize: -1,
      bodySize: e.request.body ? e.request.body.length : 0,
    },
    response: {
      status: e.response.status,
      statusText: e.response.statusText,
      httpVersion: "HTTP/1.1",
      headers: harHeaders(e.response.headers),
      content: { size: e.response.bodyText.length, mimeType: e.response.mimeType, text: e.response.bodyText },
      headersSize: -1,
      bodySize: e.response.bodyText.length,
    },
    cache: {},
    timings: { send: 0, wait: e.durationMs, receive: 0 },
  };
}

export function toHAR(session: Session): unknown {
  return {
    log: {
      version: "1.2",
      creator: { name: "open-api-mcp", version: "0.1.0" },
      entries: session.history.map(harEntry),
    },
  };
}

function jStr(s: string): string {
  return JSON.stringify(s);
}

function safeOrigin(url: string): string | undefined {
  try {
    return new URL(url).origin;
  } catch {
    return undefined;
  }
}

function jestCase(e: HttpExchange): string {
  const u = new URL(e.request.url);
  const path = u.pathname + u.search;
  const method = e.request.method.toUpperCase();

  const headerLines: string[] = [];
  let hasAuth = false;
  for (const [k, v] of Object.entries(e.request.headers)) {
    const lower = k.toLowerCase();
    if (isSensitiveHeader(k)) {
      hasAuth = true;
      continue;
    }
    if (lower === "host" || lower === "content-length") continue;
    headerLines.push(`        ${jStr(k)}: ${jStr(v)},`);
  }

  const ct = e.response.headers["content-type"] ?? e.response.mimeType ?? "";
  const isJson = /json/i.test(ct);

  const init: string[] = [`      method: ${jStr(method)},`];
  if (headerLines.length || hasAuth) {
    init.push("      headers: {", ...headerLines, "        ...authHeaders(),", "      },");
  }
  if (e.request.body !== undefined && method !== "GET" && method !== "HEAD") {
    init.push(`      body: ${jStr(e.request.body)},`);
  }

  const lines = [
    `  it(${jStr(`${method} ${path} -> ${e.response.status}`)}, async () => {`,
    `    const res = await fetch(BASE + ${jStr(path)}, {`,
    ...init,
    "    });",
    `    expect(res.status).toBe(${e.response.status});`,
  ];
  if (isJson) {
    lines.push("    const body = await res.json();", "    expect(body).toBeDefined();");
  }
  lines.push("  });");
  return lines.join("\n");
}

export function toJest(session: Session): string {
  const origin =
    (session.history[0] && safeOrigin(session.history[0].request.url)) ||
    session.spec?.baseUrl ||
    session.baseUrl ||
    "http://localhost";
  const title = session.spec?.title ?? "API";

  const header = [
    "/**",
    " * Generated by open-api-mcp from a live test session.",
    " * Replays each executed request and asserts the observed status code.",
    " * Override the target with API_BASE_URL; provide auth via API_AUTH / API_KEY / API_COOKIE.",
    " * E2E flows are intentionally excluded — this is HTTP contract replay.",
    " */",
    "",
    `const BASE = process.env.API_BASE_URL || ${jStr(origin)};`,
    "",
    "function authHeaders() {",
    "  return {",
    "    ...(process.env.API_AUTH ? { authorization: process.env.API_AUTH } : {}),",
    '    ...(process.env.API_KEY ? { "x-api-key": process.env.API_KEY } : {}),',
    "    ...(process.env.API_COOKIE ? { cookie: process.env.API_COOKIE } : {}),",
    "  };",
    "}",
    "",
  ].join("\n");

  const cases =
    session.history.length === 0
      ? '  it.todo("no requests were recorded in this session");'
      : session.history.map(jestCase).join("\n\n");

  return [header, `describe(${jStr(`${title} — contract replay`)}, () => {`, cases, "});", ""].join("\n");
}

// ---- Markdown: the full human-readable report (all planes + contract + context) ----

const BODY_CAP = 50_000; // per-body char cap so a stray multi-MB payload can't bloat the file

function pct(n: number, d: number): string {
  return d === 0 ? "—" : Math.round((n / d) * 100) + "%";
}

/** Mask common secret-bearing JSON keys (token, password, api_key, …) in a body. */
function redactBodyText(body: string): string {
  if (!body) return body;
  return body.replace(
    /("[^"]*(?:token|password|passwd|secret|api[-_]?key|authorization|client[-_]?secret)[^"]*"\s*:\s*)"(?:[^"\\]|\\.)*"/gi,
    '$1"***redacted***"',
  );
}

/** Escape a value so it stays inside one Markdown table cell. */
function mdCell(s: unknown): string {
  return String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function langFor(mime: string): string {
  if (/json/i.test(mime)) return "json";
  if (/html/i.test(mime)) return "html";
  if (/xml/i.test(mime)) return "xml";
  return "";
}

function bodyBlock(raw: string | undefined, mime: string): string {
  if (raw === undefined || raw === "") return "_(empty)_";
  const red = redactBodyText(raw);
  const capped =
    red.length > BODY_CAP ? red.slice(0, BODY_CAP) + `\n…[truncated ${red.length - BODY_CAP} chars]` : red;
  return "```" + langFor(mime) + "\n" + capped + "\n```";
}

function headerTable(headers: Record<string, string>): string {
  const red = redactHeaders(headers);
  const keys = Object.keys(red);
  if (!keys.length) return "_(none)_";
  return ["| Header | Value |", "| --- | --- |", ...keys.map((k) => `| ${mdCell(k)} | ${mdCell(red[k])} |`)].join("\n");
}

/** Compact ddmmyy stamp for the default report filename. */
export function ddmmyy(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return p(d.getDate()) + p(d.getMonth() + 1) + p(d.getFullYear() % 100);
}

export function toMarkdown(session: Session, generatedAt: string): string {
  const passed = session.results.filter((r) => r.ok).length;
  const failed = session.results.length - passed;
  const spec = session.spec;
  const target = spec?.baseUrl ?? session.baseUrl ?? "_(not set)_";
  const wsFrames = [...session.sockets.values()].reduce((n, s) => n + s.frames.length, 0);
  const opCount = Object.keys(spec?.deref?.paths ?? spec?.bundled?.paths ?? {}).length;
  const synthesized = spec?.source === "synthesized (in-memory)";
  const overall =
    session.results.length === 0 ? "— no assertions" : failed === 0 ? "✅ PASS" : `❌ FAIL (${failed})`;

  const o: string[] = [];
  o.push("# API Test Report", "");
  o.push("| | |", "| --- | --- |");
  o.push(`| **Generated** | ${generatedAt} |`);
  o.push(`| **Target** | ${mdCell(target)} |`);
  if (spec) o.push(`| **Contract** | ${mdCell(`${spec.title ?? "untitled"} ${spec.version ?? ""} (${spec.kind})`)} |`);
  o.push(`| **Result** | ${overall} |`);
  o.push("");

  o.push("## Summary", "");
  o.push("| Metric | Value |", "| --- | --- |");
  o.push(`| Assertions | ${session.results.length} (✅ ${passed} / ❌ ${failed} — ${pct(passed, session.results.length)} pass) |`);
  o.push(`| HTTP requests | ${session.history.length} |`);
  o.push(`| Sockets (WS / Socket.IO) | ${session.sockets.size} (${wsFrames} frames) |`);
  o.push(`| Browser network events | ${session.net.length} |`);
  o.push(`| Browser console messages | ${session.console.length} |`);
  o.push("");

  o.push("## Contract & Test Oracle", "");
  if (!spec) {
    o.push("_No spec was loaded — requests were issued freeform, without schema-drift validation._", "");
  } else {
    o.push(`- **Title:** ${spec.title ?? "untitled"} ${spec.version ?? ""}`.trim());
    o.push(`- **Kind:** ${spec.kind}`);
    o.push(
      `- **Source:** ${spec.source}` +
        (synthesized
          ? " — synthesized from the target's source code, held in memory (no file written to the project). This derived contract is the mock/oracle every response below was validated against."
          : ""),
    );
    o.push(`- **Base URL:** ${spec.baseUrl ?? "_(none)_"}`);
    o.push(`- **Operations covered by the contract:** ${opCount}`);
    o.push("");
  }

  o.push("## Assertions", "");
  if (!session.results.length) {
    o.push("_No assertions were recorded this session._", "");
  } else {
    o.push("| # | Result | Name | Detail | Time |", "| --- | --- | --- | --- | --- |");
    session.results.forEach((r, i) =>
      o.push(`| ${i + 1} | ${r.ok ? "✅" : "❌"} | ${mdCell(r.name)} | ${mdCell(r.detail)} | ${new Date(r.at).toISOString()} |`),
    );
    o.push("");
  }

  o.push("## HTTP Exchanges", "");
  if (!session.history.length) {
    o.push("_No HTTP requests were made._", "");
  } else {
    session.history.forEach((e, i) => {
      o.push(`### ${i + 1}. \`${e.request.method} ${e.request.url}\``, "");
      o.push(`- **Status:** ${`${e.response.status} ${e.response.statusText}`.trim()}`);
      o.push(`- **Duration:** ${e.durationMs} ms`);
      o.push(`- **Started:** ${new Date(e.startedAt).toISOString()}`, "");
      o.push("**Request headers**", "", headerTable(e.request.headers), "");
      o.push("**Request body**", "", bodyBlock(e.request.body, e.request.headers["content-type"] ?? ""), "");
      o.push("**Response headers**", "", headerTable(e.response.headers), "");
      o.push("**Response body**", "", bodyBlock(e.response.bodyText, e.response.mimeType), "");
    });
  }

  if (session.sockets.size) {
    o.push("## WebSocket / Socket.IO", "");
    for (const s of session.sockets.values()) {
      const transport = s.kind === "socketio" ? "Socket.IO" : "WebSocket";
      const state = s.open
        ? "open"
        : `closed${s.closeInfo ? ` (code ${s.closeInfo.code}${s.closeInfo.reason ? `, ${s.closeInfo.reason}` : ""})` : ""}`;
      o.push(`### \`${s.id}\` — ${transport} — ${mdCell(s.url)}`, "");
      o.push(`- **State:** ${state}`);
      if (s.kind === "socketio" && s.namespace) o.push(`- **Namespace:** ${mdCell(s.namespace)}`);
      o.push(`- **Frames:** ${s.frames.length}`, "");
      if (s.frames.length) {
        o.push("| # | Dir | Time | Event | Data |", "| --- | --- | --- | --- | --- |");
        s.frames.forEach((f, i) =>
          o.push(
            `| ${i + 1} | ${f.dir === "in" ? "⬇ in" : "⬆ out"} | ${new Date(f.at).toISOString()} | ${mdCell(f.event ?? "")} | ${mdCell(redactBodyText(f.data)).slice(0, 500)} |`,
          ),
        );
        o.push("");
      }
    }
  }

  if (session.net.length) {
    o.push("## Browser — Network", "");
    o.push("| # | At | Kind | Method | Status | URL |", "| --- | --- | --- | --- | --- | --- |");
    session.net.forEach((n, i) =>
      o.push(`| ${i + 1} | ${new Date(n.at).toISOString()} | ${n.kind} | ${n.method ?? ""} | ${n.status ?? ""} | ${mdCell(n.url)} |`),
    );
    o.push("");
  }

  if (session.console.length) {
    o.push("## Browser — Console", "");
    o.push("| # | At | Type | Message |", "| --- | --- | --- | --- |");
    session.console.forEach((c, i) =>
      o.push(`| ${i + 1} | ${new Date(c.at).toISOString()} | ${c.type} | ${mdCell(c.text)} |`),
    );
    o.push("");
  }

  o.push("## Session Context", "");
  const authKeys = Object.keys(session.auth.headers);
  o.push(`- **Auth headers:** ${authKeys.length ? authKeys.join(", ") + " (values redacted)" : "_(none)_"}`);
  o.push(`- **Cookies:** ${Object.keys(session.auth.cookies).length}`);
  if (session.oauth.grant)
    o.push(`- **OAuth grant:** ${session.oauth.grant}${session.oauth.tokenUrl ? ` @ ${session.oauth.tokenUrl}` : ""}`);
  if (session.tracePath)
    o.push(`- **Browser trace:** \`${session.tracePath}\` — open with \`npx playwright show-trace ${session.tracePath}\``);
  o.push("", "---", `_Generated by open-api-mcp — secrets redacted, bodies capped at ${BODY_CAP.toLocaleString("en-US")} chars._`, "");

  return o.join("\n");
}

export async function exportReport(
  session: Session,
  args: { format: "junit" | "har" | "json" | "jest" | "markdown"; path?: string },
): Promise<unknown> {
  let content: string;
  let defaultPath: string | undefined;
  if (args.format === "junit") content = toJUnit(session);
  else if (args.format === "har") content = JSON.stringify(toHAR(session), null, 2);
  else if (args.format === "jest") content = toJest(session);
  else if (args.format === "markdown") {
    const now = new Date();
    content = toMarkdown(session, now.toISOString());
    defaultPath = `test-report-${ddmmyy(now)}.md`; // the persisted final report
  } else content = JSON.stringify(buildReport(session), null, 2);

  // Markdown is the deliverable final report: always write a file, defaulting to test-report-ddmmyy.md.
  const path = args.path ?? defaultPath;
  if (path) {
    await writeFile(path, content, "utf8");
    return { written: path, format: args.format, bytes: content.length };
  }
  return { format: args.format, content };
}
